sonar.projectKey=simple-node-app
sonar.projectName=simple-node-app

# Where your source code lives
sonar.sources=.

# SonarQube server URL
sonar.host.url=http://host.docker.internal:9000

# Encoding
sonar.sourceEncoding=UTF-8

# 🚫 Tell Sonar to ignore big / useless folders
sonar.exclusions=node_modules/**,coverage/**,dependency-check-report/**,**/*.test.js
